refactor:`hpmn` rename to `evo`
dashpay/FAQs pull request #10
Opened 2023-10-04 14:01 UTC by ogabrielides

Aligned with DIP-0028 (https://github.com/dashpay/dips/pull/145) and implementation (https://github.com/dashpay/dash/pull/5508)

2023-10-04 14:52 UTC, UdjinM6 requested changes
pls see below and maybe rename the file itself too (would have to adjust https://github.com/dashpay/dips/pull/145 after that)

2023-10-04 14:52 UTC, UdjinM6 commented on Platform/platform-activation-hpmn-faq.md
> +25. **What is a High-Performance Masternode (EvoNode)?**
```suggestion
25. **What is an Evolution Node (EvoNode)?**
```

2023-10-04 14:52 UTC, UdjinM6 commented on Platform/platform-activation-hpmn-faq.md
>  26. **What are the main advantages of choosing one of the High-Performance Masternode solutions?**
```suggestion
26. **What are the main advantages of choosing one of the Evolution Node solutions?**
```

2023-10-04 14:52 UTC, UdjinM6 commented on Platform/platform-activation-hpmn-faq.md
>  | | Every node must run Platform | High Performance 4k | High Performance 10k
```suggestion
| | Every node must run Platform | Evolution Node 4k | Evolution Node 10k
```

2023-10-04 15:22 UTC, thephez reviewed
Generally I would change:
- Evolution Node(s) -> Evolution masternode(s)
- EvoNode -> evonode

2023-10-05 07:31 UTC, ogabrielides commented
> Generally I would change:
> 
> * Evolution Node(s) -> Evolution masternode(s)
> * EvoNode -> evonode

Followed this guideline in order to be aligned with DIP-0028.

2023-10-05 10:38 UTC, UdjinM6 approved these changes
LGTM

2023-10-05 14:01 UTC, thephez requested changes
A few more small ones

2023-10-05 14:01 UTC, thephez commented on Platform/platform-activation-evonodes-faq.md
> +The higher collateral requirement does not enforce higher performance. Rather, Masternodes have an economic incentive to follow the specs recommended by DCG: if a node wasn’t performing sufficiently,
```suggestion
The higher collateral requirement does not enforce higher performance. Rather, Masternodes have an economic incentive to follow the specs recommended by DCG: if a node wasn’t performing sufficiently, it would start lagging behind the rest of the network, fail to produce blocks, and miss out on rewards. Thus an evonode will be required to be stronger than the current average standard masternode in order to receive rewards. A second point is that higher collateral shows a higher stake in the project which should push evonode owners to have a higher incentive to have more performant hardware servicing Dash Platform.
```

2023-10-05 14:01 UTC, thephez commented on Platform/platform-activation-evonodes-faq.md
> +30. **What would the governance voting power of a evonode be compared to a regular masternode?**
```suggestion
30. **What would the governance voting power of an evonode be compared to a regular masternode?**
```

2023-10-05 14:06 UTC, ogabrielides commented
> A few more small ones

Damn, I don't know how I managed to skip those :see_no_evil:

2023-10-05 14:08 UTC, thephez approved these changes
👍

2023-10-05 14:36 UTC, UdjinM6 approved these changes

2023-10-09 16:46 UTC, merged